language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  #- 0.6
 # - 0.8
  #- 5.0
  - 0.8
env:
    global:
      - CITY:'PUNE'
      - AWS_BUCKET=$TRAVIS_BRANCH
      - AWS_REGION=$TRAVIS_BRANCH

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  irc: "irc.freenode.org#travis"
